theme: jekyll-theme-slate
title: CodeX Academy Competency Library

description: Online home of CodeX Academy's library of technical competencies.
show_downloads: false
markdown: kramdown
collections: 
  levels:
    output: true
    sort_by: number
  level_categories:
    output: true
    sort_by: difficulty
    
